apiVersion: v1
kind: Deployment
metadata:
  name: router-v1
  labels: 
    app: router
    version: v1
specs: 
  replicas: 3
  selector:
    matchlabels: 
      app: router
      version: v1
    template:
      metadata:
        name: router-v1
        labels: 
          app: router
          version: v1

        specs:
          container:
          - name: backend
            image: router:v1
            imagePullPolicy: Never
            ports: 
            - containerPort: 8000
